"""
Kubernetes Live Integration — Day 3
Fetches real pod logs, node events, and executes K8s patches.
Falls back gracefully when K8S_ENABLED=false.

Three capabilities:
  1. fetch_pod_logs()       — stream recent logs from a crashing pod
  2. fetch_node_events()    — get Warning events for a node
  3. apply_k8s_patch()      — apply the AI-generated YAML (dry-run or live)
  4. get_node_gpu_status()  — check allocatable GPU count on a node
"""

from __future__ import annotations

import subprocess
import tempfile
from pathlib import Path
from typing import Any

from app.core.config import settings
from app.core.logger import get_logger

logger = get_logger(__name__)


def _kubectl(*args: str, input_data: str | None = None) -> tuple[int, str, str]:
    """
    Run a kubectl command. Returns (returncode, stdout, stderr).
    Respects KUBECONFIG_PATH if set.
    """
    cmd = ["kubectl"]
    if settings.kubeconfig_path:
        cmd += ["--kubeconfig", settings.kubeconfig_path]
    cmd += list(args)

    logger.info(f"kubectl {' '.join(args)}")
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        input=input_data,
        timeout=30,
    )
    if result.returncode != 0:
        logger.warning(f"kubectl error: {result.stderr[:200]}")
    return result.returncode, result.stdout, result.stderr


async def fetch_pod_logs(
    pod: str,
    namespace: str = "ml-serving",
    lines: int = 200,
    previous: bool = True,
) -> str:
    """
    Fetch recent logs from a pod (or its previous crashed container).
    Returns log text, or empty string if unavailable.
    """
    if not settings.k8s_enabled:
        logger.info("K8s disabled — returning empty pod logs (using fixture logs instead)")
        return ""

    args = ["logs", pod, "-n", namespace, f"--tail={lines}"]
    if previous:
        args.append("--previous")

    rc, stdout, stderr = _kubectl(*args)
    if rc == 0 and stdout:
        logger.info(f"Fetched {len(stdout.splitlines())} log lines from {pod}/{namespace}")
        return stdout

    # If --previous fails, try current container
    rc, stdout, stderr = _kubectl("logs", pod, "-n", namespace, f"--tail={lines}")
    return stdout if rc == 0 else f"# Could not fetch logs for {pod}: {stderr}"


async def fetch_node_events(node: str, namespace: str = "default") -> str:
    """
    Fetch Warning events for a node (last 1 hour).
    """
    if not settings.k8s_enabled:
        return ""

    rc, stdout, _ = _kubectl(
        "get", "events",
        "--field-selector", f"involvedObject.name={node}",
        "--field-selector", "type=Warning",
        "-n", namespace,
        "--sort-by=.lastTimestamp",
    )
    return stdout if rc == 0 else ""


async def get_node_gpu_status(node: str) -> dict[str, Any]:
    """
    Return allocatable and capacity GPU count for a node.
    """
    if not settings.k8s_enabled:
        return {"k8s_enabled": False, "node": node}

    rc, stdout, _ = _kubectl(
        "get", "node", node,
        "-o", "jsonpath={.status.capacity.nvidia\\.com/gpu},{.status.allocatable.nvidia\\.com/gpu},{.status.conditions[-1].type},{.status.conditions[-1].status}",
    )
    if rc != 0:
        return {"error": "could not fetch node status"}

    parts = stdout.split(",")
    return {
        "node": node,
        "gpu_capacity": int(parts[0]) if parts[0].isdigit() else None,
        "gpu_allocatable": int(parts[1]) if len(parts) > 1 and parts[1].isdigit() else None,
        "last_condition": parts[2] if len(parts) > 2 else None,
        "condition_status": parts[3] if len(parts) > 3 else None,
    }


async def apply_k8s_patch(
    patch_yaml: str,
    dry_run: bool = True,
    incident_id: str = "",
) -> dict[str, Any]:
    """
    Apply a multi-document YAML patch to the cluster.

    Args:
        patch_yaml: Multi-document YAML string (AI-generated by recommend_fix node)
        dry_run:    If True (default), runs --dry-run=server — safe to call always
        incident_id: For audit logging

    Returns dict with:
        success: bool
        dry_run: bool
        applied_resources: list of resource types applied
        output: kubectl output
        error: error message if failed
    """
    if not settings.k8s_enabled:
        return {
            "success": False,
            "dry_run": dry_run,
            "reason": "K8S_ENABLED=false — enable to apply patches to a real cluster",
            "patch_preview": patch_yaml[:500],
        }

    # Write patch to a temp file
    with tempfile.NamedTemporaryFile(
        mode="w", suffix=".yaml", prefix=f"gpu-copilot-{incident_id}-", delete=False
    ) as f:
        f.write(patch_yaml)
        patch_file = f.name

    try:
        args = ["apply", "-f", patch_file]
        if dry_run:
            args += ["--dry-run=server"]

        rc, stdout, stderr = _kubectl(*args)

        # Parse which resources were applied
        applied = []
        for line in stdout.splitlines():
            if "configured" in line or "created" in line or "unchanged" in line or "(dry run)" in line:
                applied.append(line.strip())

        result = {
            "success": rc == 0,
            "dry_run": dry_run,
            "incident_id": incident_id,
            "applied_resources": applied,
            "output": stdout[:2000],
            "error": stderr[:500] if rc != 0 else None,
        }

        if rc == 0:
            logger.info(
                f"K8s patch {'dry-run' if dry_run else 'APPLIED'} for {incident_id}: "
                f"{len(applied)} resources"
            )
        else:
            logger.error(f"K8s patch failed for {incident_id}: {stderr[:200]}")

        return result

    finally:
        Path(patch_file).unlink(missing_ok=True)


async def cordon_node(node: str, dry_run: bool = True) -> dict[str, Any]:
    """Cordon a node to prevent new pod scheduling."""
    if not settings.k8s_enabled:
        return {"success": False, "reason": "K8S_ENABLED=false", "command": f"kubectl cordon {node}"}

    args = ["cordon", node]
    if dry_run:
        args += ["--dry-run=client"]
    rc, stdout, stderr = _kubectl(*args)
    return {"success": rc == 0, "dry_run": dry_run, "node": node, "output": stdout, "error": stderr if rc != 0 else None}


async def drain_node(node: str, dry_run: bool = True) -> dict[str, Any]:
    """Drain a node, evicting all non-daemonset pods."""
    if not settings.k8s_enabled:
        return {"success": False, "reason": "K8S_ENABLED=false", "command": f"kubectl drain {node} --ignore-daemonsets"}

    args = ["drain", node, "--ignore-daemonsets", "--delete-emptydir-data"]
    if dry_run:
        args += ["--dry-run=client"]
    rc, stdout, stderr = _kubectl(*args)
    return {"success": rc == 0, "dry_run": dry_run, "node": node, "output": stdout, "error": stderr if rc != 0 else None}


async def fetch_all_logs_for_alert(alert: "AlertPayload", extra_lines: int = 200) -> list[str]:  # noqa: F821
    """
    Entry point called by the /alert/webhook route.
    Fetches pod logs + node events, combining into a log list.
    Falls back to fixture logs when K8S_ENABLED=false.
    """
    if not settings.k8s_enabled:
        from app.core.fixtures import load_logs
        return load_logs([
            "fixtures/logs/cuda_ecc_error.txt",
            "fixtures/logs/oom_killed.txt",
            "fixtures/logs/node_pressure.txt",
        ])

    logs = []
    if alert.alerts:
        pod = alert.alerts[0].labels.pod
        namespace = alert.alerts[0].labels.namespace or "ml-serving"
        if pod:
            pod_log = await fetch_pod_logs(pod, namespace, lines=extra_lines)
            if pod_log:
                logs.append(pod_log)

    node = alert.commonLabels.get("node", "")
    if node:
        events = await fetch_node_events(node)
        if events:
            logs.append(events)

    return logs or ["# No live logs available"]
